apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech-deploy
  namespace: purdueproject 
spec:
  selector:
    matchLabels:
      app: abc_deploy
  replicas: 6
  template:
    metadata:
      labels:
        app: abc_deploy
    spec:
      containers:
      - name: abc-app
        image: naveencldock/purdueproject
        ports:
        - containerPort: 8080
