apiVersion: v1
kind: Service
metadata:
  name: abc-nodeport-svc
  namespace: purdueproject 
spec:
  selector:
    app: abc_deploy
  ports:
    - protocol: TCP
      port: 8585
      targetPort: 8080
  type: NodePort

